security:
    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login
        users_in_memory:
            memory:
                users:
                    admin:
                        password: 'strong-password'
                        roles: 'ROLE_ADMIN'
                    user:
                        password: 'password'
                        roles: 'ROLE_USER'

    password_hashers:
        App\Entity\User: auto
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        token:
            pattern: ^/api/v1/token
            security: false
        healthCheck:
            pattern: ^/api/v1/health-check
            security: false
        jwtSecured: &jwtSecured
            pattern: ^/api/v(3|4)
            stateless: true
            custom_authenticator: App\Security\JWTTokenAuthenticator
            provider: app_user_provider
        clientApi:
            <<: *jwtSecured
            pattern: ^/api/v1/tasks
        serverApi:
            pattern: ^/server-api
            http_basic:
                realm: Secured Area
            lazy: true
            provider: users_in_memory

    access_control:
        - { path: ^/api/v4/save-user, roles: ROLE_ADMIN }

