security:
    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login
        users_in_memory:
            memory:
                users:
                    admin:
                        password: 'my_pass'
                        roles: 'ROLE_ADMIN'
                    user:
                        password: 'other_pass'
                        roles: 'ROLE_USER'

    password_hashers:
        App\Entity\User: auto
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        token:
            pattern: ^/api/v1/token
            security: false
        basic:
            pattern: ^/api/v4/get-users
            stateless: true
            customAuthenticator: App\Security\JWTTokenAuthenticator
            provider: app_user_provider
        main:
            http_basic:
                realm: Secured Area
            lazy: true
            provider: users_in_memory

    access_control:
        - { path: ^/api/v4/save-user, roles: ROLE_ADMIN }

